required = ["github.com/pulumi/pulumi-aws"]

[[override]]
  name = "github.com/pulumi/pulumi"
  revision = "304af9cdf192f484ffd7cc29d980524172009093"

[[override]]
  name = "github.com/pulumi/pulumi-aws"
  revision = "b7e10bc410eee37a1003a2b015c11f07f4f93a5c"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"
