required = ["github.com/pulumi/pulumi-aws"]

[[override]]
  name = "github.com/pulumi/pulumi"
  revision = "208b7296bee8f876b48950e9df12869adc32a76a"

[[override]]
  name = "github.com/pulumi/pulumi-aws"
  revision = "e212f3f40fe1d8b981bb073ac6d00ea1b91f08b5"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"
