required = ["github.com/pulumi/pulumi-aws"]

[[override]]
  name = "github.com/pulumi/pulumi"
  revision = "7aedf80fa2ea10ada802cfb77acb42b148e7429b"

[[override]]
  name = "github.com/pulumi/pulumi-aws"
  revision = "7321b8ba728c3fde3676d6d484c3fc8b67a4c9d9"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"
