required = ["github.com/pulumi/pulumi-aws"]

[[override]]
  name = "github.com/pulumi/pulumi"
  revision = "444ebdd1b52b72bbffa1a637626cdd77687afc70"

[[override]]
  name = "github.com/pulumi/pulumi-aws"
  revision = "124dd9cf8678ed343f70c7c661bfe7535adacbd2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"
