required = ["github.com/pulumi/pulumi-aws"]

[[override]]
  name = "github.com/pulumi/pulumi"
  version = "=v0.9.10"

[[override]]
  name = "github.com/pulumi/pulumi-aws"
  version = "=v0.9.10"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"
