required = ["github.com/pulumi/pulumi-aws"]

[[override]]
  name = "github.com/pulumi/pulumi"
  revision = "ce05cce77f06439e139bbc035fd3649f7bd23d4f"

[[override]]
  name = "github.com/pulumi/pulumi-aws"
  revision = "d5639d8f229009ba3b3503205b3483c13a403664"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"
