required = ["github.com/pulumi/pulumi-aws"]

[[override]]
  name = "github.com/pulumi/pulumi"
  revision = "9695c1666dd8d23ed15ac8768f7738f9e86717cb"

[[override]]
  name = "github.com/pulumi/pulumi-aws"
  revision = "2f53649a19020567192945f8eef1c9c27d70c4d2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"
