required = ["github.com/pulumi/pulumi-aws"]

[[override]]
  name = "github.com/pulumi/pulumi"
  branch = "release/0.11"

[[override]]
  name = "github.com/pulumi/pulumi-aws"
  branch = "release/0.11"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"
