required = ["github.com/pulumi/pulumi-aws"]

[[override]]
  name = "github.com/pulumi/pulumi"
  branch = "master"

[[override]]
  name = "github.com/pulumi/pulumi-aws"
  branch = "master"

[[override]]
  name = "github.com/hashicorp/terraform"
  version = "0.10.8"
