required = ["github.com/pulumi/pulumi-aws"]

[[override]]   
  name = "github.com/pulumi/pulumi"
  revision = "eec99c3ca9831940a3c54285b1b49980d24b0c2d"

[[override]]
  name = "github.com/pulumi/pulumi-aws"
  revision = "d1f492ede9c9a1ae716c2b6d41c30b201555513d"

