required = ["github.com/pulumi/pulumi-aws"]

[[override]]
  name = "github.com/pulumi/pulumi"
  revision = "446d419c268851de0a5a39a73818580d33cd63a7"

[[override]]
  name = "github.com/pulumi/pulumi-aws"
  revision = "28fa2fe1289ee3c01b7239211fdd02ec3bdb1dc7"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"
