required = ["github.com/pulumi/pulumi-aws"]

[[override]]
  name = "github.com/pulumi/pulumi"
  revision = "1ff84c1991295589b85f0ce6bf90a1b09d5a63c0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"
